#!/usr/bin/env bash

gen_main() {
	E_ARGS=16
	E_CD_FAILED=17

	cd "$(dirname "$0")" || exit $E_CD_FAILED

	mkdir CopyURL.iconset
	sips -z 16 16 icon.png --out CopyURL.iconset/icon_16x16.png
	sips -z 32 32 icon.png --out CopyURL.iconset/icon_16x16@2x.png
	sips -z 32 32 icon.png --out CopyURL.iconset/icon_32x32.png
	sips -z 64 64 icon.png --out CopyURL.iconset/icon_32x32@2x.png
	sips -z 128 128 icon.png --out CopyURL.iconset/icon_128x128.png
	sips -z 256 256 icon.png --out CopyURL.iconset/icon_128x128@2x.png
	sips -z 256 256 icon.png --out CopyURL.iconset/icon_256x256.png
	sips -z 512 512 icon.png --out CopyURL.iconset/icon_256x256@2x.png
	sips -z 512 512 icon.png --out CopyURL.iconset/icon_512x512.png
	cp icon.png CopyURL.iconset/icon_512x512@2x.png
	iconutil -c icns CopyURL.iconset
}

gen_main "$@"
